apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dl357s240-nodejs 
  janus-idp.io/tekton: dl357s240-nodejs
  backstage.io/kubernetes-id: dl357s240-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dl357s240-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  