apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dl357s240-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dl357s240-nodejs 
  name: dl357s240-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dl357s240-nodejs 
